#  _____ _   _ _____ __  __ _____ ____
# |_   _| | | | ____|  \/  | ____/ ___|
#   | | | |_| |  _| | |\/| |  _| \___ \
#   | | |  _  | |___| |  | | |___ ___) |
#   |_| |_| |_|_____|_|  |_|_____|____/

# Fecha: 2024-05-07
# Autor: Prof. Franklin Cedeño Cocho

#========================================  COLORES

thm_fg="#D8DEE9"
thm_bg="#3B4252"
color_azul="#89b4fa"
color_blanco="#D8DEE9"
color_gris="#f5c2e7"
color_gris1="#ABB2BF"
color_gris2="#cdd6f4"
color_gris3="#3B4252"
color_magenta="#cba6f7"
color_naranja="#fab387"
color_negro="#1b1d2b"
color_rojo="red"
color_rosa="#f5c2e7" 

#======================================== 󰢦 BARRA

set -g status "on"
set-option -g status-style bg=default 
set -g status-fg "${thm_fg}"
set -g status-interval 3 # Actualizar barra de estado cada 3 seg (default 15)
set -g status-position top
set -g status-justify centre # Ventanas en el centro

set -g status-left-length 200 # Default 10
set -g status-left "#{?client_prefix,#[fg=${color_naranja}],}  :#S"
#set -g status-left "#[fg=${color_blanco},bg=default]#{?client_prefix,#[fg=${color_magenta}],}  :#S"

set -g status-right-length 200 # Default 10
set -g status-right "󰃰 %a-%d |  %R | 󰚥 #(cat /sys/class/power_supply/BAT1/capacity)\% "
#set -g status-right "#[fg=${color_blanco},bg=default]󰃰 %a-%d |  %R | 󰚥 #(cat /sys/class/power_supply/BAT1/capacity)\% "

#========================================  VENTANAS

set -g base-index 1  # Índice de inicio
set-window-option -g pane-base-index 1
set -g renumber-windows on  # Reenumerar al cerrar una ventana

set -g window-status-format "  #I:#W"
set -g window-status-current-format "#{?window_zoomed_flag,#[fg=${color_naranja}],#[fg=${color_azul}]} #[underscore]#I:#W"
set -g window-status-bell-style "fg=${color_rojo}"

#========================================  PANELES

set -g pane-base-index 1  # Índice de inicio
set -g pane-border-style "fg=${color_gris3}"
set -g pane-active-border-style "fg=${color_gris1}"

#========================================  MENSAJES

set -g message-style "fg=${color_magenta},bg=${color_gris3},align=centre"
set -g message-command-style "fg=${color_magenta},bg=${thm_bg},align=centre"

#========================================  󱑍 RELOJ

set -g clock-mode-colour "${color_azul}"

#========================================  MODOS

set -g mode-style "fg=${color_azul} bg=${color_negro} bold"
