# _____ __  __ _   ___  __   ____ ___  _   _ _____ ___ ____
#|_   _|  \/  | | | \ \/ /  / ___/ _ \| \ | |  ___|_ _/ ___|
#  | | | |\/| | | | |\  /  | |  | | | |  \| | |_   | | |  _
#  | | | |  | | |_| |/  \  | |__| |_| | |\  |  _|  | | |_| |
#  |_| |_|  |_|\___//_/\_\  \____\___/|_| \_|_|   |___\____|


# Fecha: 2025-10-03
# Autor: Franklin Cedeño Cocho

#========================================  Set

source-file ~/.config/tmux/themes.conf
source-file ~/.config/tmux/keymaps.conf

set -g default-terminal "${TERM}" # Terminal por defecto
set -ga terminal-overrides ",*:RGB" # Habilitar color verdadero para compatibilidad con terminales
set -g mouse on # Habiliar mouse
set -g set-clipboard on	# Usa el portapapeles del sistema

#========================================  Sesiones

set -g detach-on-destroy off  # Salir de tmux al cerrar sessión

#======================================== 󰩦 Plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

#set -g @resurrect-capture-pane-contens 'on'
#set -g @resurrect-restore 'on'

# Todos los complementos están instalados en ~/.tmux/plugins/
# prefix + I
# - Instala nuevos complementos desde GitHub o cualquier otro repositorio git
# - Actualiza el entorno TMUX
# prefix + U: actualiza el(los) complemento(s)
# prefix + alt + u: eliminar/desinstalar complementos que no están en la lista de complementos
run '~/.config/tmux/plugins/tpm/tpm'

