#!/bin/bash

#===================================== Sources


#===================================== Commands


#===================================== Export

# Con la opción --tmux, fzf se iniciará en una ventana emergente de tmux. 
# --tmux [center|top|bottom|left|right][,SIZE[%]][,SIZE[%][,border-native]]
#fzf --tmux center         # Center, 50% width and height
#fzf --tmux 80%            # Center, 80% width and height
#fzf --tmux 100%,50%       # Center, 100% width and 50% height
#fzf --tmux left,40%       # Left, 40% width
#fzf --tmux left,40%,90%   # Left, 40% width, 90% height
#fzf --tmux top,40%        # Top, 40% height
#fzf --tmux bottom,80%,40% # Bottom, 80% width, 40% height

export FZF_DEFAULT_OPTS="--reverse"
#export FZF_DEFAULT_OPTS="--height 40% --tmux bottom,40% --layout reverse --border top"
#export FZF_DEFAULT_OPTS="--tmux center"
#export FZF_DEFAULT_COMMAND='ag -l --hidden --exclude -g ""'
